import 'package:fantasyf1/core/app_export.dart';import 'package:fantasyf1/widgets/app_bar/appbar_image.dart';import 'package:fantasyf1/widgets/app_bar/appbar_image_3.dart';import 'package:fantasyf1/widgets/app_bar/custom_app_bar.dart';import 'package:fantasyf1/widgets/custom_elevated_button.dart';import 'package:fantasyf1/widgets/custom_outlined_button.dart';import 'package:fantasyf1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CambiarcontraseA2screenScreen extends StatelessWidget {CambiarcontraseA2screenScreen({Key? key}) : super(key: key);

TextEditingController fileController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 39.v), SizedBox(height: 232.v, width: 320.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgLogo, height: 64.v, width: 280.h), SizedBox(height: 16.v), SizedBox(width: 303.h, child: Text("msg_formula_1_fantasy".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.displayLarge))]))), CustomAppBar(height: 40.v, leadingWidth: 60.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftPrimary, margin: EdgeInsets.only(left: 20.h), onTap: () {onTapArrowleftone(context);}), actions: [AppbarImage3(svgPath: ImageConstant.imgHome, margin: EdgeInsets.fromLTRB(20.h, 8.v, 20.h, 7.v))])])), SizedBox(height: 42.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 5.v), child: Column(children: [Container(margin: EdgeInsets.symmetric(horizontal: 8.h), decoration: AppDecoration.outlinePrimary3, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_recupera_tu_cuenta".tr, style: CustomTextStyles.headlineMediumInter), Container(width: 247.h, margin: EdgeInsets.fromLTRB(31.h, 10.v, 31.h, 3.v), child: Text("msg_introduce_el_c_digo".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleSmall15))])), SizedBox(height: 13.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_c_digo_verificaci_n".tr, style: CustomTextStyles.titleSmallPoppinsOnErrorContainer), SizedBox(height: 7.v), CustomTextFormField(controller: fileController, hintText: "lbl_466_005".tr, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 14.v, 8.h, 14.v), child: CustomImageView(svgPath: ImageConstant.imgFileBlue400)), prefixConstraints: BoxConstraints(maxHeight: 48.v))]), SizedBox(height: 7.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_tiempo_restante".tr, style: CustomTextStyles.bodyMediumInterPrimary)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_5_00_minutos".tr, style: CustomTextStyles.bodyMediumInterRed400))])), CustomElevatedButton(text: "lbl_siguiente_2_3".tr, margin: EdgeInsets.only(left: 10.h, top: 55.v, right: 8.h), onTap: () {onTapSiguiente23(context);}), CustomOutlinedButton(height: 40.v, text: "msg_reenviar_c_digo".tr, margin: EdgeInsets.only(left: 10.h, top: 15.v, right: 8.h))]))))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowleftone(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the cambiarcontraseA3screenScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [Navigator] widget
/// to push the named route for the cambiarcontraseA3screenScreen.
onTapSiguiente23(BuildContext context) { Navigator.pushNamed(context, AppRoutes.cambiarcontraseA3screenScreen); } 
 }
