name: FantasyF1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  supabase_flutter: ^1.10.25
  get: ^4.6.6
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: ^2.4.9
  clipboard: ^0.1.3
  riverpod: ^2.4.9
  image_cropper: ^4.0.1
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  uuid: ^4.2.1
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  flutter_avif: ^2.2.0
  aligned_tooltip: 0.0.1
  app_links: 3.4.1
  auto_size_text: 3.0.0
  badges: 2.0.2
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_native_splash: 2.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  functions_client: 1.3.2
  go_router: 7.1.1
  google_fonts: 4.0.3
  gotrue: 1.12.6
  hive: 2.2.3
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  postgrest: 1.5.2
  provider: 6.0.5
  realtime_client: 1.4.0
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6

  storage_client: 1.5.4
  supabase: 1.11.11
  timeago: 3.2.2
  universal_io: 2.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1
  xml: 6.3.0

  carousel_slider: 4.2.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter_icons:
  android: true
  ios: true
  windows: true
  image_path_windows: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/circuitos/
    - assets/images/banderas/
    - assets/images/carruseles/carrusel_s01/
    - assets/images/pilotos/
    - assets/images/s_bienvenida/
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: 'Fuentes Formula 1'
      fonts:
          - asset: assets/fonts/Formula1-Wide_web_0.ttf
            weight: 200
          - asset: assets/fonts/Formula1-Regular_web_0.ttf
          - asset: assets/fonts/Formula1-Bold_web_0.ttf
            weight: 700

    - family: IconosCustom
      fonts:
            - asset: assets/fonts/IconosCustom.ttf
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Formula1
      fonts: 
        - asset: assets/fonts/Formula1DisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/Formula1DisplayBold.ttf
          weight: 500
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Jacques Francois
      fonts: 
        - asset: assets/fonts/JacquesFrancoisRegular.ttf
          weight: 400
