// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7CfYj5vDjMtempj-1kx55i_ibpDiek0',
    appId: '1:221753940404:web:b18b4e1372244efb57fae1',
    messagingSenderId: '221753940404',
    projectId: 'fantasyf1-cd80e',
    authDomain: 'fantasyf1-cd80e.firebaseapp.com',
    databaseURL: 'https://fantasyf1-cd80e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fantasyf1-cd80e.appspot.com',
    measurementId: 'G-TCRG9JGFDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAW-BWiOjso6i-P_csiykpxH5vS_-5oek',
    appId: '1:221753940404:android:c158ca74dad6659657fae1',
    messagingSenderId: '221753940404',
    projectId: 'fantasyf1-cd80e',
    databaseURL: 'https://fantasyf1-cd80e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fantasyf1-cd80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXoGWzg93PZi-4QPn9evOmxQIStL0wP4',
    appId: '1:221753940404:ios:50f6ddc2d86300b857fae1',
    messagingSenderId: '221753940404',
    projectId: 'fantasyf1-cd80e',
    databaseURL: 'https://fantasyf1-cd80e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fantasyf1-cd80e.appspot.com',
    iosBundleId: 'com.fantasyf.app',
  );
}
